---
Name: silverstripe-gallery
---
PaulSchulz\SilverStripe\Gallery\Pages\GalleryPage:
  optimized_width: 1920
  desired_height: 200
PaulSchulz\SilverStripe\Gallery\Views\GalleryImage:
  margin: 10
---